project_id = "aliz-hw-shahmeet"
region     = "us-central1"
zone       = "us-central1-a"
config_path = "~/.kube/config"
k8s_yaml = "deploy-nexus-kubernetes.yaml"
bucket_name = "aliz-hw-shahmeet-nexus-bucket" 
