apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels: 
    group: {{ .Values.app.group }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: {{ .Values.app.service.nodePort }}
    port: {{ .Values.app.service.port }}
    protocol: {{ .Values.app.container.protocol }}
    targetPort: {{ .Values.app.service.port }}
  selector:
    group: {{ .Values.app.group }}
  sessionAffinity: None
  type: {{ .Values.app.service.type }}