
app:
  name: nexus-web
  group: nexus-web
  replicaCount: 1
  container:
    image: shahmeetk/nexus_demo
    port: 8081
    protocol: TCP
  service:
    type: LoadBalancer
    port: 8081
    nodePort: 32077
  volume:
    name: nexus-volume
    kind: PersistentVolumeClaim
    mountPath: /nexus-volume
    pvc:
      name: nexus-pvc
      accessMode: ReadWriteOnce
      storage: 2Gi
      storageClassName: standard

  
